### ISSUE TITLE
Wrong contentLength while using oklog 0.2.1

### ISSUE THREAD

**Issue by ghost** [simonpercic/OkLog#12]
I use raw `response.body().byteStream()` to download file from server using OkHttp.
There is some debug output:

```
                        target = response.body().contentLength();
                        logger.debug("target(contentLength): {}", target);
```

With oklog 0.2.1 it prints:

`target(contentLength): 2595205`

while

`Content-Length: 1506615`

But using 1.0.1:

`target(contentLength): 1506615`

New version fixed my issue.

Write it just to let you know about this strange bug as I can't find anything about it in changelog.

**Comment by simonpercic** [comment]
Thank you for the info. 

OkLog/3 has been completely rewritten in 1.0.0, based on OkHttp's HttpLoggingInterceptor implementation. As part of that rewrite, many issues have hopefully been resolved. Glad to hear that has resolved the problem with incorrect contentLength as well. 👍 

Will close this issue since it's fixed in a released version. Cheers.
