### ISSUE TITLE
Add support for non-Android projects

### ISSUE THREAD

**Issue by PDDStudio** [simonpercic/OkLog#29]
Hi there,

This library looks really nice and convenient and I would really like to be able to use it in my (not Android based) project(s).
OkHttp doesn't have any dependencies related to Android, so it can be used in pure Java-Projects as well.

I didn't have a look at this library's dependencies in detail, but except of Timber _(which is unfortunately bound to Android, too)_ there is nothing that requires this awesome component to be for pure Android projects only.

Any thoughts about this?

Regards

**Comment by simonpercic** [comment]
Hi,

thank you for the compliments! 

Actually, I am planning on removing the dependency on Android, opening the usage of OkLog to non-Android projects as well!

The first step in this was introducing proper integration tests, since that is done now, I can move on with swapping out Android dependencies with confidence that I won't break any existing functionality. It shouldn't be that difficult, so I hope I can accomplish it soon-ish. 

Thank you for re-confirming the appeal of doing so.

Stay tuned!

**Comment by PDDStudio** [comment]
Alright, great! Thanks for your fast response, if you need any help please let me know.

**Comment by simonpercic** [comment]
Hi,

OkLog 2.3.0 now (finally!) supports pure Java and Kotlin projects: [Android and Java/Kotlin support](https://github.com/simonpercic/OkLog#android-and-javakotlin-support).

You can use the new libs `oklog-java` and `oklog3-java` that don't depend on Android:
```groovy
compile 'com.github.simonpercic:oklog-java:2.3.0'
compile 'com.github.simonpercic:oklog3-java:2.3.0'
```

Cheers!
